[versions]
java = "21" # must be an integer

kotlin = "2.2.21"
kotlin-forge = "5.12.0"

# Minecraft

minecraft = { strictly="1.21.1" }

architectury = "13.0.8"
architectury-plugin = "3.4.164"
architectury-loom = "1.9-SNAPSHOT"

neoforge = "21.1.111"
neoforge-dependency = "21.1.111" # for neoforge.mods.toml

# mods

hexcasting = "0.12.0-devel-pre-39"
hexcasting-dependency = "0.12.0-devel-pre-39"

paucal = "0.7.1-pre-27"

patchouli = "1.21.1-92-NEOFORGE"

mixinExtras = "0.5.0"
clothConfig = "15.0.130"
caelus = "7.0.1+1.21.1"
inline = "1.21.1-1.2.2-neoforge"
emi = "1.1.22+1.21.1"
hexical = "2.0.0"
hexpose = "1.0.0"

# other non-Minecraft dependencies

findbugs-jsr305 = "3.0.2" # for @Nonnull
asm = "9.5"
dotenv = "2.0.0" # for template.env debugger keys
shadow = "7.1.2"
modPublish = "0.5.1"
pkpcpbp = "0.1.0-pre-87"

lsp4j = "0.23.0"
ktor = "3.3.3"
kotlinx-io = "0.8.0"

dokka = "2.1.0"
plantuml = "1.2025.10"

[bundles]
asm = ["asm", "asm-analysis", "asm-commons", "asm-tree", "asm-util"]
# must contain all transitive deps so they can be included in the production jar
lsp4j = ["lsp4j", "lsp4j-debug", "lsp4j-jsonrpc", "lsp4j-jsonrpc-debug"]
ktor = ["ktor-network", "ktor-network-jvm", "ktor-utils-jvm", "ktor-io-jvm", "kotlinx-io-core-jvm", "kotlinx-io-bytestring-jvm"]

[libraries]
kotlin-stdlib = { module="org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref="kotlin" }
kotlin-forge  = { module="thedarkcolour:kotlinforforge-neoforge", version.ref="kotlin-forge" }

minecraft = { module="com.mojang:minecraft", version.ref="minecraft" }

architectury        = { module="dev.architectury:architectury", version.ref="architectury" }
architectury-neoforge = { module="dev.architectury:architectury-neoforge", version.ref="architectury" }

neoforge = { module="net.neoforged:neoforge", version.ref="neoforge" }

patchouli-neoforge = { module="vazkii.patchouli:Patchouli", version.ref="patchouli" }

caelus             = { module="com.illusivesoulworks.caelus:caelus-neoforge", version.ref="caelus" }

mixinExtras-common = { module="io.github.llamalad7:mixinextras-common", version.ref="mixinExtras" }
mixinExtras-neoforge  = { module="io.github.llamalad7:mixinextras-neoforge", version.ref="mixinExtras" }

clothConfig-common = { module="me.shedaniel.cloth:cloth-config", version.ref="clothConfig" }
clothConfig-neoforge  = { module="me.shedaniel.cloth:cloth-config-neoforge", version.ref="clothConfig" }

emi-xplat  = { module="dev.emi:emi-xplat-intermediary", version.ref="emi" }
emi-neoforge  = { module="dev.emi:emi-neoforge", version.ref="emi" }

hexical = { module="libs:hexical", version.ref="hexical" }

hexpose = { module = "miyucomics.hexpose:hexpose", version.ref="hexpose" }

findbugs-jsr305 = { module="com.google.code.findbugs:jsr305", version.ref="findbugs-jsr305" }

asm          = { module="org.ow2.asm:asm", version.ref="asm" }
asm-analysis = { module="org.ow2.asm:asm-analysis", version.ref="asm" }
asm-commons  = { module="org.ow2.asm:asm-commons", version.ref="asm" }
asm-tree     = { module="org.ow2.asm:asm-tree", version.ref="asm" }
asm-util     = { module="org.ow2.asm:asm-util", version.ref="asm" }

lsp4j               = { module="org.eclipse.lsp4j:org.eclipse.lsp4j", version.ref="lsp4j" }
lsp4j-debug         = { module="org.eclipse.lsp4j:org.eclipse.lsp4j.debug", version.ref="lsp4j" }
lsp4j-jsonrpc       = { module="org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc", version.ref="lsp4j" }
lsp4j-jsonrpc-debug = { module="org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc.debug", version.ref="lsp4j" }

ktor-network     = { module="io.ktor:ktor-network", version.ref="ktor" }
ktor-network-jvm = { module="io.ktor:ktor-network-jvm", version.ref="ktor" }
ktor-utils-jvm = { module="io.ktor:ktor-utils-jvm", version.ref="ktor" }
ktor-io-jvm = { module="io.ktor:ktor-io-jvm", version.ref="ktor" }
kotlinx-io-core-jvm = { module="org.jetbrains.kotlinx:kotlinx-io-core-jvm", version.ref="kotlinx-io" }
kotlinx-io-bytestring-jvm = { module="org.jetbrains.kotlinx:kotlinx-io-bytestring-jvm", version.ref="kotlinx-io" }

pkpcpbp = { module="at.petra-k.pkpcpbp:PKPCPBP", version.ref="pkpcpbp" }

dokka-base = { module="org.jetbrains.dokka:dokka-base", version.ref="dokka" }
dokka-core = { module="org.jetbrains.dokka:dokka-core", version.ref="dokka" }

dokka-kotlinAsJava = { module="org.jetbrains.dokka:kotlin-as-java-plugin", version.ref="dokka" }

plantuml = { module="net.sourceforge.plantuml:plantuml", version.ref="plantuml" }

[plugins]
kotlin-jvm = { id="org.jetbrains.kotlin.jvm", version.ref="kotlin" }

dokka = { id="org.jetbrains.dokka", version.ref="dokka" }

architectury      = { id="architectury-plugin", version.ref="architectury-plugin" }
architectury-loom = { id="dev.architectury.loom", version.ref="architectury-loom" }

dotenv     = { id="co.uzzu.dotenv.gradle", version.ref="dotenv" }
shadow     = { id="com.github.johnrengelman.shadow", version.ref="shadow" }
modPublish = { id="me.modmuss50.mod-publish-plugin", version.ref="modPublish" }
